### ISSUE TITLE
cuda out of memory error

### ISSUE THREAD

**Issue by zhaozilong2zl** [SJTU-ViSYS-team/VisFly#9]
Thanks for VisFly!

Is there a minimum GPU memory limit for training in VisFly? i currently using 4060 with 8GB memory but get the OutOfMemoryError below, but my GPU seems did not run in full memory when training (20% in monitoring window),did i miss something to correctly using VisFly?
after i try `python examples/cluttered_flight/rl.py -t 1`,i get error below:

Using cuda device
VisFly/datasets/spy_datasets/configs/garage_simple_l_medium/garage_simple_low_m_0.scene_instance.json
[16:54:23:808170]:[Error]:[Metadata] StageAttributesManager.cpp(89)::registerObjectFinalize : Render asset template handle `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/stages/../../stages/garage.glb` specified in stage template with handle :/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/stages/garage.stage_config.jsondoes not correspond to any existing file or primitive render asset, so StageAttributes registration is aborted.
[16:54:23:809961]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Object Template> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/self_define_objects` so unable to load templates from that path.
[16:54:23:810243]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Articulated Object> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/hab_fetch_1.0/robots/fetch_no_base.urdf` so unable to load templates from that path.
[16:54:23:829296]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Scene Instance> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/box_simple` so unable to load templates from that path.
[16:54:23:829311]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Scene Instance> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/box_test` so unable to load templates from that path.
[16:54:23:830646]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Scene Instance> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/garage_simple_low_m` so unable to load templates from that path.
[16:54:23:831518]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_00.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831529]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_01.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831537]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_02.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831545]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_03.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831552]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_04.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831559]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_05.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831566]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_06.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831574]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_07.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831582]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_08.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831591]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_09.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831603]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_10.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831612]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_11.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831620]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_12.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831630]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_13.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831638]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_14.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831646]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_15.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831653]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_16.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831660]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_17.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831668]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_18.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831675]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_19.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831683]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_20.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
Renderer: NVIDIA GeForce RTX 4060/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 535.183.01
Using optional features:
    GL_ARB_vertex_array_object
    GL_ARB_separate_shader_objects
    GL_ARB_robustness
    GL_ARB_texture_storage
    GL_ARB_texture_view
    GL_ARB_framebuffer_no_attachments
    GL_ARB_invalidate_subdata
    GL_ARB_texture_storage_multisample
    GL_ARB_multi_bind
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_texture_filter_anisotropic
    GL_KHR_debug
    GL_KHR_parallel_shader_compile
    GL_NV_depth_buffer_float
Using driver workarounds:
    no-forward-compatible-core-context
    nv-egl-incorrect-gl11-function-pointers
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
[16:54:23:869495]:[Warning]:[Metadata] MetadataMediator.cpp(587)::getFilePathForHandle : <getNavmeshPathByHandle> : Unable to find file path for empty_stage_navmesh , so returning empty string.
[16:54:23:913358]:[Warning]:[Sim] Simulator.cpp(596)::instanceStageForSceneAttributes : The active scene does not contain semantic annotations : activeSemanticSceneID_ = 0
Logging to /home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/examples/cluttered_flight/saved/PPO_9
---------------------------------                                               
| rollout/           |          |
|    ep_len_mean     | 61.9     |
|    ep_rew_mean     | -3.47    |
|    success_rate    | 0        |
| time/              |          |
|    fps             | 3813     |
|    iterations      | 1        |
|    time_elapsed    | 6        |
|    total_timesteps | 24576    |
---------------------------------
  0%|                              | 24576/10000000.0 [00:07<47:46, 3479.74it/s]
Traceback (most recent call last):
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/examples/cluttered_flight/rl.py", line 157, in <module>
    main()
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/examples/cluttered_flight/rl.py", line 116, in main
    model.learn(training_params["learning_step"])
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/algorithms/ppo.py", line 1002, in learn
    return super().learn(
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/algorithms/ppo.py", line 970, in learn
    return super().learn(
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/algorithms/ppo.py", line 624, in learn
    self.train()
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/algorithms/ppo.py", line 1120, in train
    loss.backward()
  File "/home/ltx/anaconda3/envs/VisFly/lib/python3.9/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/home/ltx/anaconda3/envs/VisFly/lib/python3.9/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 244.00 MiB. GPU 0 has a total capacity of 7.73 GiB of which 228.50 MiB is free. Including non-PyTorch memory, this process has 6.59 GiB memory in use. Of the allocated memory 5.90 GiB is allocated by PyTorch, and 469.82 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

Using cuda device
VisFly/datasets/spy_datasets/configs/garage_simple_l_medium/garage_simple_low_m_0.scene_instance.json
[16:54:23:808170]:[Error]:[Metadata] StageAttributesManager.cpp(89)::registerObjectFinalize : Render asset template handle `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/stages/../../stages/garage.glb` specified in stage template with handle :/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/stages/garage.stage_config.jsondoes not correspond to any existing file or primitive render asset, so StageAttributes registration is aborted.
[16:54:23:809961]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Object Template> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/self_define_objects` so unable to load templates from that path.
[16:54:23:810243]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Articulated Object> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/hab_fetch_1.0/robots/fetch_no_base.urdf` so unable to load templates from that path.
[16:54:23:829296]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Scene Instance> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/box_simple` so unable to load templates from that path.
[16:54:23:829311]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Scene Instance> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/box_test` so unable to load templates from that path.
[16:54:23:830646]:[Warning]:[Metadata] AttributesManagerBase.h(457)::buildAttrSrcPathsFromJSONAndLoad : <Scene Instance> : No Glob path result found for `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets/configs/garage_simple_low_m` so unable to load templates from that path.
[16:54:23:831518]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_00.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831529]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_01.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831537]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_02.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831545]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_03.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831552]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_04.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831559]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_05.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831566]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_06.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831574]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_07.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831582]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_08.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831591]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_09.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831603]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_10.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831612]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_11.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831620]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_12.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831630]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_13.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831638]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_14.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831646]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_15.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831653]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_16.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831660]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_17.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831668]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_18.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831675]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_19.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
[16:54:23:831683]:[Error]:[Metadata] SceneDatasetAttributesManager.cpp(304)::validateMap : `navmesh_instances` Value : `navmeshes/v3_sc4_staging_20.navmesh` not found on disk as absolute path or relative to `/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/../datasets/spy_datasets`
Renderer: NVIDIA GeForce RTX 4060/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 535.183.01
Using optional features:
    GL_ARB_vertex_array_object
    GL_ARB_separate_shader_objects
    GL_ARB_robustness
    GL_ARB_texture_storage
    GL_ARB_texture_view
    GL_ARB_framebuffer_no_attachments
    GL_ARB_invalidate_subdata
    GL_ARB_texture_storage_multisample
    GL_ARB_multi_bind
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_texture_filter_anisotropic
    GL_KHR_debug
    GL_KHR_parallel_shader_compile
    GL_NV_depth_buffer_float
Using driver workarounds:
    no-forward-compatible-core-context
    nv-egl-incorrect-gl11-function-pointers
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
[16:54:23:869495]:[Warning]:[Metadata] MetadataMediator.cpp(587)::getFilePathForHandle : <getNavmeshPathByHandle> : Unable to find file path for empty_stage_navmesh , so returning empty string.
[16:54:23:913358]:[Warning]:[Sim] Simulator.cpp(596)::instanceStageForSceneAttributes : The active scene does not contain semantic annotations : activeSemanticSceneID_ = 0
Logging to /home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/examples/cluttered_flight/saved/PPO_9
---------------------------------                                               
| rollout/           |          |
|    ep_len_mean     | 61.9     |
|    ep_rew_mean     | -3.47    |
|    success_rate    | 0        |
| time/              |          |
|    fps             | 3813     |
|    iterations      | 1        |
|    time_elapsed    | 6        |
|    total_timesteps | 24576    |
---------------------------------
  0%|                              | 24576/10000000.0 [00:07<47:46, 3479.74it/s]
Traceback (most recent call last):
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/examples/cluttered_flight/rl.py", line 157, in <module>
    main()
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/examples/cluttered_flight/rl.py", line 116, in main
    model.learn(training_params["learning_step"])
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/algorithms/ppo.py", line 1002, in learn
    return super().learn(
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/algorithms/ppo.py", line 970, in learn
    return super().learn(
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/algorithms/ppo.py", line 624, in learn
    self.train()
  File "/home/ltx/UAV_3D/habitat_sim-based/My_Project_Using_VisFly/VisFly/utils/algorithms/ppo.py", line 1120, in train
    loss.backward()
  File "/home/ltx/anaconda3/envs/VisFly/lib/python3.9/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/home/ltx/anaconda3/envs/VisFly/lib/python3.9/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 244.00 MiB. GPU 0 has a total capacity of 7.73 GiB of which 228.50 MiB is free. Including non-PyTorch memory, this process has 6.59 GiB memory in use. Of the allocated memory 5.90 GiB is allocated by PyTorch, and 469.82 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
"

**Comment by zhaozilong2zl** [comment]
i mange to fix it by decrease batch_size
